// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/// Drift table definition and data class for a plant.
///
/// Mirrors the Android Room `@Entity(tableName = "plants")` class defined in
/// `data/Plant.kt`. The [Plant] data class is auto-generated by drift from
/// the [Plants] table definition.
library;

import 'package:drift/drift.dart';

// ---------------------------------------------------------------------------
// Table definition
// ---------------------------------------------------------------------------

/// Drift table definition for the `plants` table.
///
/// Mirrors the Android Room `Plant` entity:
/// - `id`               → primary key (text)
/// - `name`             → plant display name
/// - `description`      → plant description (HTML allowed)
/// - `grow_zone_number` → USDA hardiness zone (1–13)
/// - `watering_interval`→ days between waterings (default 7)
/// - `image_url`        → URL for the plant hero image (default empty)
class Plants extends Table {
  /// The unique identifier for this plant (e.g. `"apple"`).
  TextColumn get id => text()();

  /// The human-readable name of the plant.
  TextColumn get name => text()();

  /// A description of the plant (may contain HTML).
  TextColumn get description => text()();

  /// The USDA hardiness zone in which this plant thrives.
  IntColumn get growZoneNumber => integer()();

  /// How often the plant should be watered, in days.
  IntColumn get wateringInterval => integer().withDefault(const Constant(7))();

  /// URL for the plant's hero image.
  TextColumn get imageUrl => text().withDefault(const Constant(''))();

  @override
  Set<Column<Object>> get primaryKey => {id};
}

// ---------------------------------------------------------------------------
// Domain model extension
// ---------------------------------------------------------------------------

/// Extension methods on the drift-generated [Plant] data class.
extension PlantExtension on Plant {
  /// Determines whether the plant should be watered.
  ///
  /// Returns `true` if [since] is strictly after
  /// [lastWateringDate] + [wateringInterval] days.
  ///
  /// Mirrors `Plant.shouldBeWatered()` from the Android implementation.
  bool shouldBeWatered({
    required DateTime since,
    required DateTime lastWateringDate,
  }) =>
      since.isAfter(lastWateringDate.add(Duration(days: wateringInterval)));

  @override
  String toString() => name;
}
