// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/// Drift table definition and data class for a plant.
///
/// Mirrors the Android Room `@Entity(tableName = "plants")` class defined in
/// `data/Plant.kt`. The [Plant] data class is auto-generated by drift from
/// the [Plants] table definition.
///
/// ## Code generation
/// Run `flutter pub run build_runner build --delete-conflicting-outputs`
/// to regenerate `app_database.g.dart` after modifying this file.
library;

import 'package:drift/drift.dart';

// ---------------------------------------------------------------------------
// Table definition
// ---------------------------------------------------------------------------

/// Drift table definition for the `plants` table.
///
/// Mirrors the Android Room `Plant` entity:
/// - `id`               → primary key (text)
/// - `name`             → plant display name
/// - `description`      → plant description (HTML allowed)
/// - `grow_zone_number` → USDA hardiness zone (1–13)
/// - `watering_interval`→ days between waterings (default 7)
/// - `image_url`        → URL for the plant hero image (default empty)
///
/// The drift-generated [Plant] data class is a plain Dart class with
/// immutable fields, equivalent to a Kotlin `data class`.
class Plants extends Table {
  /// The unique identifier for this plant (e.g. `"apple"`).
  ///
  /// Mirrors `@PrimaryKey @ColumnInfo(name = "id") val plantId: String`.
  TextColumn get id => text()();

  /// The human-readable name of the plant.
  TextColumn get name => text()();

  /// A description of the plant (may contain HTML).
  TextColumn get description => text()();

  /// The USDA hardiness zone in which this plant thrives.
  ///
  /// Valid values are 1–13. See [getZoneForLatitude] for zone calculation.
  IntColumn get growZoneNumber => integer()();

  /// How often the plant should be watered, in days.
  ///
  /// Defaults to 7 (once a week), mirroring the Android default.
  IntColumn get wateringInterval => integer().withDefault(const Constant(7))();

  /// URL for the plant's hero image.
  ///
  /// Defaults to an empty string when no image is available.
  TextColumn get imageUrl => text().withDefault(const Constant(''))();

  @override
  Set<Column<Object>> get primaryKey => {id};
}

// ---------------------------------------------------------------------------
// Domain model extension
// ---------------------------------------------------------------------------

/// Extension methods on the drift-generated [Plant] data class.
///
/// These methods add domain logic to the auto-generated data class,
/// mirroring the methods defined directly on the Android `Plant` data class.
extension PlantExtension on Plant {
  /// Determines whether the plant should be watered.
  ///
  /// Returns `true` if [since] is strictly after
  /// [lastWateringDate] + [wateringInterval] days.
  ///
  /// Mirrors `Plant.shouldBeWatered(since: Calendar, lastWateringDate: Calendar)`
  /// from the Android implementation. The Android version uses `Calendar.add(DAY_OF_YEAR, ...)`
  /// which is equivalent to Dart's [Duration] addition.
  ///
  /// Example:
  /// ```dart
  /// final plant = Plant(id: 'tomato', name: 'Tomato', ..., wateringInterval: 2);
  /// final now = DateTime.now();
  /// final lastWatered = now.subtract(const Duration(days: 3));
  /// plant.shouldBeWatered(since: now, lastWateringDate: lastWatered); // true
  /// ```
  bool shouldBeWatered({
    required DateTime since,
    required DateTime lastWateringDate,
  }) =>
      since.isAfter(lastWateringDate.add(Duration(days: wateringInterval)));

  /// Returns the plant's name as its string representation.
  ///
  /// Mirrors `override fun toString() = name` in the Android implementation.
  String toDisplayString() => name;
}
